import { runPluginContractTests } from "@jackmazac/opencode-host-adapter/contract-test";

runPluginContractTests({
  pluginPath: new URL("./index.ts", import.meta.url).href,
  pluginName: "conductor",
  stubInput: () => ({
    client: {},
    directory: "/tmp/opencode-conductor-contract-test",
  }),
  expectedTools: [
    "audit_write",
    "audit_read",
    "audit_done",
    "audit_progress_update",
    "audit_progress_read",
    "audit_progress_done",
    "handoff_write",
    "handoff_read",
    "handoff_done",
    "journal_write",
    "journal_read",
    "journal_done",
    "progress_update",
    "progress_read",
    "progress_done",
    "run_init",
    "run_update",
    "run_finish",
    "status_write",
    "status_read",
    "status_done",
    "persist_subplan",
    "read_subplan",
    "discard_subplan",
    "persist_final_plan",
    "read_final_plan",
    "discard_final_plan",
    "persist_brainstorm",
    "read_brainstorm",
    "discard_brainstorm",
    "persist_design",
    "read_design",
    "discard_design",
    "conflict_context",
    "context_usage",
    "lifecycle_concord_ingest",
    "explore_fast",
    "discard_explore_cache",
    "commit",
    "artifact_index",
    "run_list",
    "session_init",
    "drift_check",
    "plan_validate",
    "journal_search",
  ],
});
